[package]
name = "convnet-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
rand = "0.8.5"
rand_distr = "0.4.3"
serde = { version = "1.0.203", features = ["derive"] }
typetag = "0.2.16"

[dev-dependencies]
image = "0.25.1"
